=== asiapicasso/projet-webdon/entreprise.dtd
<!ELEMENT entreprise (nom, description, services, equipe)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT services (service+)>
<!ELEMENT equipe (employe+)>
<!ELEMENT service (#PCDATA)>
<!ELEMENT employe (posteOccupe, donneesPersonnelles, parcoursProfessionnel, formations, competencesLinguistiques, services, competencesTechniques)>
<!ELEMENT posteOccupe (#PCDATA)>
<!ELEMENT donneesPersonnelles (nom, prenom, dateDeNaissance, adresse)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT dateDeNaissance (#PCDATA)>
<!ELEMENT adresse (rue, numero, npa)>
<!ELEMENT rue (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT npa (#PCDATA)>
<!ELEMENT parcoursProfessionnel (experienceEnMois)>
<!ELEMENT experienceEnMois (#PCDATA)>
<!ELEMENT formations (ecole+)>
<!ELEMENT ecole (nom, diplome)>
<!ELEMENT diplome (#PCDATA)>
<!ELEMENT competencesLinguistiques (langue+)>
<!ELEMENT langue (nom, niveau)>
<!ELEMENT niveau (#PCDATA)>
<!ELEMENT competencesTechniques (competence+)>
<!ELEMENT competence (#PCDATA)>

=== asiapicasso/projet-webdon/entreprise.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entreprise SYSTEM "entreprise.dtd">
<entreprise>
    <nom>CreaSite</nom>
    <description>Notre entreprise est spécialisée dans la création de site web et d'identité graphique. Nous concevons des sites internet de qualité, adaptés à vos besoins et à votre budget. Nous vous proposons des sites internet clé en main, des sites e-commerce, des sites vitrines, des sites à thème, des sites d'entreprise, des sites de présentation...</description>

    <services>
        <service>Création de site internet</service>
        <service>Création d'identité graphique</service>
        <service>Création de logo</service>
        <service>Création de carte de visite</service>
        <service>Création de flyers</service>
        <service>Création de plaquette</service>
    </services>

    <departement>
        <employe>
            <posteOccupe>Informaticien</posteOccupe>

            <donneesPersonnelles>
                <nom>Dupont</nom>
                <prenom>Jean</prenom>
                <dateDeNaissance>24-03-1997</dateDeNaissance>
                <adresse>
                    <rue>Rue de la Paix 4</rue>
                    <npa>1006</npa>
                </adresse>
            </donneesPersonnelles>

            <parcoursProfessionnel>
                <experienceEnMois>36</experienceEnMois>
            </parcoursProfessionnel>

            <formations>
                <ecole>
                    <nom>Université de Paris</nom>
                    <diplome>Bac +5</diplome>
                </ecole>
            </formations>

            <competencesLinguistiques>
                <langue>
                    <nom>Anglais</nom>
                    <niveau>Avancé</niveau>
                </langue>
            </competencesLinguistiques>

            <services>
                <service>Développement</service>
                <service>Maintenance</service>
            </services>

            <competencesTechniques>
                <competence>Java</competence>
                <competence>C++</competence>
                <competence>Python</competence>
            </competencesTechniques>

        </employe>

        <employe>
            <posteOccupe>Graphiste</posteOccupe>

            <donneesPersonnelles>
                <nom>Dupont</nom>
                <prenom>Jeanne</prenom>
                <dateDeNaissance>08-10-1996</dateDeNaissance>
                <adresse>
                    <rue>Rue de la Paix 4</rue>
                    <npa>1006</npa>
                </adresse>
            </donneesPersonnelles>

            <parcoursProfessionnel>
                <experienceEnMois>36</experienceEnMois>
            </parcoursProfessionnel>

            <formations>
                <ecole>
                    <nom>Université de Paris</nom>
                    <diplome>Bac +5</diplome>
                </ecole>
            </formations>

            <competencesLinguistiques>
                <langue>
                    <nom>Anglais</nom>
                    <niveau>Basique</niveau>
                </langue>
            </competencesLinguistiques>

            <services>
                <service>Création</service>
                <service>Retouche</service>
            </services>

            <competencesTechniques>
                <competence>Photoshop</competence>
                <competence>Illustrator</competence>
                <competence>Indesign</competence>
            </competencesTechniques>
        </employe>
    </departement>
</entreprise>
